id: db838c91e6c64b78a532104f2c7f16b5
initial_creation_type: ebook
created_at: 20/05/2021
last_modified_at: 25/11/2021
source_metadata:
  title: test
  subtitle: test
  authors:
  - test
  collection: test
  publisher: test
  id: test
  cover: tmpc7w9voeq.jpg
  credit: tmp2p8gznpr.jpg
